### ISSUE TITLE
I ran `gulp` and I got errors

### ISSUE THREAD

**Issue by fifn2** [jh3y/gulp-boilerplate#31]
I ran gulp and I got the errors
```
[08:19:08] Failed to load external module @babel/register
[08:19:08] Failed to load external module babel-register
[08:19:08] Failed to load external module babel-core/register
[08:19:08] Failed to load external module babel/register
C:\Users\finnm\OneDrive\Desktop\min.io\gulp-boilerplate\gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at execute (C:\Users\finnm\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:28:18)
```

**Comment by jh3y** [comment]
Hey @fifn2 👋 
Which version of `node` were you using? That may be the issue.
